### PR TITLE
Basic implementation

### LINKED ISSUE #2: Design initial API
Should be obvious how to design this, except we need to depend upon `cowboy` or some other 3rd party HTTP library stack.

### PR DESCRIPTION
**Pull request by tank-bohr**
Fixes #2

- The API of the library is based on the [ruby](https://github.com/ipinfo/ruby) one.
- Using erlang built-in HTTP client [httpc](http://erlang.org/doc/apps/inets/http_client.html)
- The only dependency is JSON-parser [jsx](https://github.com/talentdeficit/jsx)
- Designed with Elixir usage in mind. The main handler is an elixir struct, thus it could be used for protocol implementation

❤️

### CODE REVIEW

**Comment by UmanShahzad** [comment]
Wow thanks a lot @tank-bohr !

I'm going to need some time to review this, since it's been a while since I touched Erlang code (and I never touched Elixir...). I did a skim though and it looks really well done.

Some quick comments right now:

- I see that you've taken caching into account; that's excellent. We generally allow a replaceable caching backend in SDKs, so that in this case for example the user wouldn't be forced to use ETS, but this is perfectly fine as it is for a v1.
- Prefix or suffix the cache key with a `"vsn:"` or `":vsn"` respectively where `vsn` is a number we can increment in the source, so that whenever the cache data model changes we don't risk giving back bad data in case the user's cache hasn't been flushed.

**Comment by tank-bohr** [comment]
> Prefix or suffix the cache key with a "vsn:" or ":vsn" respectively where vsn is a number we can increment in the source, so that whenever the cache data model changes we don't risk giving back bad data in case the user's cache hasn't been flushed.

@UmanShahzad I believe it's not necessary in the case of ETS-based cache. ETS lives completely in memory and you always get an empty cache after a restart

**Comment by UmanShahzad** [comment]
@tank-bohr Alright, that makes sense.

**Comment by UmanShahzad** [comment]
So this is really great, thank you again @tank-bohr for the great contribution. I don't have much else to say about the code after looking at it.

I'll hopefully try it out locally some time this upcoming week and merge it.

**Comment by UmanShahzad** [comment]
Thanks again @tank-bohr for this! It works great. I'll publish it soon on hex.pm.

**Comment by UmanShahzad** [comment]
https://hex.pm/packages/ipinfo

**Pull request merged**
